# Generated by Django 5.1.4 on 2025-01-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallname', models.CharField(max_length=255)),
                ('hallimage', models.ImageField(upload_to='halls/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('halllocation', models.CharField(max_length=255)),
            ],
        ),
    ]
